Repository FoodieLog/foodie-log-server, pull requests merged in 2023-08, with the labels that each got.

#2 엔티티 테이블 설계 완료
  build.gradle
  src/main/java/com/foodielog/server/feed/Feed.java
  src/main/java/com/foodielog/server/feed/FeedLike.java
  src/main/java/com/foodielog/server/feed/Media.java
  src/main/java/com/foodielog/server/notification/Notification.java
  src/main/java/com/foodielog/server/reply/Reply.java
  src/main/java/com/foodielog/server/report/Report.java
  src/main/java/com/foodielog/server/restaurant/Restaurant.java
  src/main/java/com/foodielog/server/restaurant/RestaurantLike.java
  src/main/java/com/foodielog/server/types/BlockReason.java
  src/main/java/com/foodielog/server/types/ContentStatus.java
  src/main/java/com/foodielog/server/types/Flag.java
  src/main/java/com/foodielog/server/types/ManagementStatus.java
  src/main/java/com/foodielog/server/types/NotificationType.java
  src/main/java/com/foodielog/server/types/ProviderType.java
  src/main/java/com/foodielog/server/types/ReportReason.java
  src/main/java/com/foodielog/server/types/ReportType.java
  src/main/java/com/foodielog/server/types/Role.java
  src/main/java/com/foodielog/server/types/UserStatus.java
  src/main/java/com/foodielog/server/types/WithDrawReason.java
  src/main/java/com/foodielog/server/user/BadgeApply.java
  src/main/java/com/foodielog/server/user/BlockUser.java
  src/main/java/com/foodielog/server/user/Follow.java
  src/main/java/com/foodielog/server/user/User.java
  src/main/java/com/foodielog/server/user/WithDrawUser.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: develop

#6 Create Issue_template
  .github/issue_template/bug_report.md
  .github/issue_template/feat_issue_template.md
Labels: 📃 Docs

#8 [Feat] #7 Exception Handler & API 응답 Util 클래스 정의
  src/main/java/com/foodielog/server/_core/error/MyExceptionHandler.java
  src/main/java/com/foodielog/server/_core/error/MyValidationHandler.java
  src/main/java/com/foodielog/server/_core/error/exception/Exception400.java
  src/main/java/com/foodielog/server/_core/error/exception/Exception401.java
  src/main/java/com/foodielog/server/_core/error/exception/Exception403.java
  src/main/java/com/foodielog/server/_core/error/exception/Exception404.java
  src/main/java/com/foodielog/server/_core/error/exception/Exception500.java
  src/main/java/com/foodielog/server/_core/util/ApiUtils.java
  src/main/java/com/foodielog/server/_core/util/DateUtils.java
  src/main/java/com/foodielog/server/_core/util/FilterResponseUtils.java
Labels: ⚙ Setting

#12 [Refactor] #11 전체 패키지 구조 수정
  src/main/java/com/foodielog/server/admin/entity/BadgeApply.java
  src/main/java/com/foodielog/server/admin/entity/BlockUser.java
  src/main/java/com/foodielog/server/admin/entity/WithDrawUser.java
  src/main/java/com/foodielog/server/admin/type/BlockReason.java
  src/main/java/com/foodielog/server/admin/type/ProcessedStatus.java
  src/main/java/com/foodielog/server/admin/type/WithDrawReason.java
  src/main/java/com/foodielog/server/feed/Feed.java
  src/main/java/com/foodielog/server/feed/FeedLike.java
  src/main/java/com/foodielog/server/feed/Media.java
  src/main/java/com/foodielog/server/feed/entity/Feed.java
  src/main/java/com/foodielog/server/feed/entity/FeedLike.java
  src/main/java/com/foodielog/server/feed/entity/Media.java
  src/main/java/com/foodielog/server/feed/type/ContentStatus.java
  src/main/java/com/foodielog/server/notification/Notification.java
  src/main/java/com/foodielog/server/notification/entity/Notification.java
  src/main/java/com/foodielog/server/notification/type/NotificationType.java
  src/main/java/com/foodielog/server/reply/Reply.java
  src/main/java/com/foodielog/server/reply/entity/Reply.java
  src/main/java/com/foodielog/server/report/Report.java
  src/main/java/com/foodielog/server/report/entity/Report.java
  src/main/java/com/foodielog/server/report/type/ReportReason.java
  src/main/java/com/foodielog/server/report/type/ReportType.java
  src/main/java/com/foodielog/server/restaurant/Restaurant.java
  src/main/java/com/foodielog/server/restaurant/RestaurantLike.java
  src/main/java/com/foodielog/server/restaurant/entity/Restaurant.java
  src/main/java/com/foodielog/server/restaurant/entity/RestaurantLike.java
  src/main/java/com/foodielog/server/types/BlockReason.java
  src/main/java/com/foodielog/server/types/ContentStatus.java
  src/main/java/com/foodielog/server/types/Flag.java
  src/main/java/com/foodielog/server/types/ManagementStatus.java
  src/main/java/com/foodielog/server/types/NotificationType.java
  src/main/java/com/foodielog/server/types/ProviderType.java
  src/main/java/com/foodielog/server/types/ReportReason.java
  src/main/java/com/foodielog/server/types/ReportType.java
  src/main/java/com/foodielog/server/types/Role.java
  src/main/java/com/foodielog/server/types/UserStatus.java
  src/main/java/com/foodielog/server/types/WithDrawReason.java
  src/main/java/com/foodielog/server/user/BadgeApply.java
  src/main/java/com/foodielog/server/user/BlockUser.java
  src/main/java/com/foodielog/server/user/Follow.java
  src/main/java/com/foodielog/server/user/User.java
  src/main/java/com/foodielog/server/user/WithDrawUser.java
  src/main/java/com/foodielog/server/user/entity/Follow.java
  src/main/java/com/foodielog/server/user/entity/User.java
  src/main/java/com/foodielog/server/user/type/Flag.java
  src/main/java/com/foodielog/server/user/type/ProviderType.java
  src/main/java/com/foodielog/server/user/type/Role.java
  src/main/java/com/foodielog/server/user/type/UserStatus.java
Labels: ♻️ Refactor

#14 [Setting] #13 멀티모듈 셋팅 완료
  application/build.gradle
  application/src/main/java/com/foodielog/application/Application.java
  application/src/main/resources/application.properties
  application/src/test/java/com/foodielog/application/ApplicationTests.java
  core/build.gradle
  core/src/main/java/com/foodielog/server/FoodieLogServerApplication.java
  core/src/main/java/com/foodielog/server/_core/error/MyExceptionHandler.java
  core/src/main/java/com/foodielog/server/_core/error/MyValidationHandler.java
  core/src/main/java/com/foodielog/server/_core/error/exception/Exception400.java
  core/src/main/java/com/foodielog/server/_core/error/exception/Exception401.java
  core/src/main/java/com/foodielog/server/_core/error/exception/Exception403.java
  core/src/main/java/com/foodielog/server/_core/error/exception/Exception404.java
  core/src/main/java/com/foodielog/server/_core/error/exception/Exception500.java
  core/src/main/java/com/foodielog/server/_core/util/ApiUtils.java
  core/src/main/java/com/foodielog/server/_core/util/DateUtils.java
  core/src/main/java/com/foodielog/server/_core/util/FilterResponseUtils.java
  core/src/main/java/com/foodielog/server/admin/entity/BadgeApply.java
  core/src/main/java/com/foodielog/server/admin/entity/BlockUser.java
  core/src/main/java/com/foodielog/server/admin/entity/WithDrawUser.java
  core/src/main/java/com/foodielog/server/admin/type/BlockReason.java
  core/src/main/java/com/foodielog/server/admin/type/ProcessedStatus.java
  core/src/main/java/com/foodielog/server/admin/type/WithDrawReason.java
  core/src/main/java/com/foodielog/server/feed/entity/Feed.java
  core/src/main/java/com/foodielog/server/feed/entity/FeedLike.java
  core/src/main/java/com/foodielog/server/feed/entity/Media.java
  core/src/main/java/com/foodielog/server/feed/type/ContentStatus.java
  core/src/main/java/com/foodielog/server/notification/entity/Notification.java
  core/src/main/java/com/foodielog/server/notification/type/NotificationType.java
  core/src/main/java/com/foodielog/server/reply/entity/Reply.java
  core/src/main/java/com/foodielog/server/report/entity/Report.java
  core/src/main/java/com/foodielog/server/report/type/ReportReason.java
  core/src/main/java/com/foodielog/server/report/type/ReportType.java
  core/src/main/java/com/foodielog/server/restaurant/entity/Restaurant.java
  core/src/main/java/com/foodielog/server/restaurant/entity/RestaurantLike.java
  core/src/main/java/com/foodielog/server/user/entity/Follow.java
  core/src/main/java/com/foodielog/server/user/entity/User.java
  core/src/main/java/com/foodielog/server/user/type/Flag.java
  core/src/main/java/com/foodielog/server/user/type/ProviderType.java
  core/src/main/java/com/foodielog/server/user/type/Role.java
  core/src/main/java/com/foodielog/server/user/type/UserStatus.java
  core/src/main/resources/application.yml
  core/src/test/java/com/foodielog/server/FoodieLogServerApplicationTests.java
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  management/build.gradle
  management/src/main/java/com/foodielog/management/ManagementApplication.java
  management/src/main/resources/application.properties
  management/src/test/java/com/foodielog/management/ManagementApplicationTests.java
  settings.gradle
Labels: ⚙ Setting

#16 [Feat] #9 Spring Security & JWT 설정
  .gitignore
  application/build.gradle
  application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java
  application/src/main/java/com/foodielog/application/user/dto/UserRequest.java
  application/src/main/java/com/foodielog/application/user/dto/UserResponse.java
  application/src/main/java/com/foodielog/application/user/service/UserService.java
  application/src/main/resources/data.sql
  core/build.gradle
  core/src/main/java/com/foodielog/server/FoodieLogServerApplication.java
  core/src/main/java/com/foodielog/server/_core/error/ErrorMessage.java
  core/src/main/java/com/foodielog/server/_core/error/exception/Exception404.java
  core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java
  core/src/main/java/com/foodielog/server/_core/security/auth/PrincipalDetails.java
  core/src/main/java/com/foodielog/server/_core/security/auth/PrincipalDetailsService.java
  core/src/main/java/com/foodielog/server/_core/security/jwt/JwtAuthenticationFilter.java
  core/src/main/java/com/foodielog/server/_core/security/jwt/JwtTokenProvider.java
  core/src/main/java/com/foodielog/server/user/entity/User.java
  core/src/main/java/com/foodielog/server/user/repository/UserRepository.java
  core/src/main/java/com/foodielog/server/user/type/Flag.java
  core/src/main/resources/application.yml
  core/src/test/java/com/foodielog/server/FoodieLogServerApplicationTests.java
  management/build.gradle
  management/src/main/resources/data.sql
Labels: ✨ Feature

#21 [Fix] #19 JWT 토큰 권한 체크 오류 해결
  core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java
Labels: 🐛 Bug

#31 [Refactor] #30 controller, exception 응답 포맷 수정
  application/src/main/java/com/foodielog/application/feed/controller/FeedController.java
  application/src/main/java/com/foodielog/application/reply/controller/ReplyController.java
  application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java
  core/src/main/java/com/foodielog/server/_core/error/MyValidationHandler.java
  core/src/main/java/com/foodielog/server/_core/error/exception/ValidationException.java
  core/src/main/java/com/foodielog/server/_core/util/ApiUtils.java
Labels: ♻️ Refactor

#40 [Refactor] #36 userDTO 구조 수정
  application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java
  application/src/main/java/com/foodielog/application/user/controller/UserController.java
  application/src/main/java/com/foodielog/application/user/dto/ExistsEmailDTO.java
  application/src/main/java/com/foodielog/application/user/dto/ExistsNickNameDTO.java
  application/src/main/java/com/foodielog/application/user/dto/LoginDTO.java
  application/src/main/java/com/foodielog/application/user/dto/SendCodeDTO.java
  application/src/main/java/com/foodielog/application/user/dto/UserFeedListDTO.java
  application/src/main/java/com/foodielog/application/user/dto/UserProfileDTO.java
  application/src/main/java/com/foodielog/application/user/dto/UserRequest.java
  application/src/main/java/com/foodielog/application/user/dto/UserThumbnailDTO.java
  application/src/main/java/com/foodielog/application/user/dto/VerifiedCodeDTO.java
  application/src/main/java/com/foodielog/application/user/service/UserAuthService.java
  application/src/main/java/com/foodielog/application/user/service/UserOauthService.java
  application/src/main/java/com/foodielog/application/user/service/UserService.java
Labels: ♻️ Refactor

#43 [Feat] #42 Build jobs 추가
  .github/workflows/pr-test.yml
Labels: ⚙ Setting, ✨ Feature

#53 [Fix] #52 맛집 중복 체크 오류 수정
  application/src/main/java/com/foodielog/application/feed/service/FeedService.java
Labels: 🐛 Bug

#60 [Feat] #59 LoginDTO 응답 id값 추가
  application/src/main/java/com/foodielog/application/user/dto/LoginDTO.java
Labels: ✨ Feature

#75 [Fix] #70 맛집 좋아요, 좋아요 취소 수정
  application/src/main/java/com/foodielog/application/restaurant/controller/RestaurantController.java
  application/src/main/java/com/foodielog/application/restaurant/dto/LikeRestaurantDTO.java
  application/src/main/java/com/foodielog/application/restaurant/dto/UnlikeRestaurantDTO.java
  application/src/main/java/com/foodielog/application/restaurant/service/RestaurantService.java
Labels: 🐛 Bug

#76 [Bug] #74 댓글 조회, 댓글 삭제 기능 수정
  application/src/main/java/com/foodielog/application/reply/service/ReplyService.java
  core/src/main/java/com/foodielog/server/reply/entity/Reply.java
  core/src/main/java/com/foodielog/server/reply/repository/ReplyRepository.java
Labels: 🐛 Bug

#80 [Fix] #78 탈퇴, 차단한 유저 로그인 막기
  application/src/main/java/com/foodielog/application/user/service/UserAuthService.java
  application/src/main/java/com/foodielog/application/user/service/UserOauthService.java
  core/src/main/java/com/foodielog/server/_core/security/auth/PrincipalDetailsService.java
  core/src/main/java/com/foodielog/server/user/repository/UserRepository.java
Labels: 🐛 Bug

#83 [Feat] #81 유저 검색 구현
  application/src/main/java/com/foodielog/application/user/controller/UserController.java
  application/src/main/java/com/foodielog/application/user/dto/UserSearchDTO.java
  application/src/main/java/com/foodielog/application/user/service/UserService.java
  core/src/main/java/com/foodielog/server/user/repository/UserRepository.java
Labels: ✨ Feature

#102 [Refactor] #95 User DTO 구조 리팩토링
  application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java
  application/src/main/java/com/foodielog/application/user/controller/UserController.java
  application/src/main/java/com/foodielog/application/user/controller/UserSettingController.java
  application/src/main/java/com/foodielog/application/user/dto/ChangeNotificationDTO.java
  application/src/main/java/com/foodielog/application/user/dto/ChangePasswordDTO.java
  application/src/main/java/com/foodielog/application/user/dto/ChangeProfileDTO.java
  application/src/main/java/com/foodielog/application/user/dto/CheckBadgeApplyDTO.java
  application/src/main/java/com/foodielog/application/user/dto/CreateBadgeApplyDTO.java
  application/src/main/java/com/foodielog/application/user/dto/ExistsEmailDTO.java
  application/src/main/java/com/foodielog/application/user/dto/ExistsNickNameDTO.java
  application/src/main/java/com/foodielog/application/user/dto/LoginDTO.java
  application/src/main/java/com/foodielog/application/user/dto/LogoutDTO.java
  application/src/main/java/com/foodielog/application/user/dto/ReissueDTO.java
  application/src/main/java/com/foodielog/application/user/dto/ResetPasswordDTO.java
  application/src/main/java/com/foodielog/application/user/dto/SendCodeDTO.java
  application/src/main/java/com/foodielog/application/user/dto/SignUpDTO.java
  application/src/main/java/com/foodielog/application/user/dto/UserProfileDTO.java
  application/src/main/java/com/foodielog/application/user/dto/UserRestaurantListDTO.java
  application/src/main/java/com/foodielog/application/user/dto/UserSearchDTO.java
  application/src/main/java/com/foodielog/application/user/dto/VerifiedCodeDTO.java
  application/src/main/java/com/foodielog/application/user/dto/WithdrawDTO.java
  application/src/main/java/com/foodielog/application/user/dto/request/ChangeNotificationReq.java
  application/src/main/java/com/foodielog/application/user/dto/request/ChangePasswordReq.java
  application/src/main/java/com/foodielog/application/user/dto/request/ChangeProfileReq.java
  application/src/main/java/com/foodielog/application/user/dto/request/LoginReq.java
  application/src/main/java/com/foodielog/application/user/dto/request/ReissueReq.java
  application/src/main/java/com/foodielog/application/user/dto/request/ResetPasswordReq.java
  application/src/main/java/com/foodielog/application/user/dto/request/SignUpReq.java
  application/src/main/java/com/foodielog/application/user/dto/request/WithdrawReq.java
  application/src/main/java/com/foodielog/application/user/dto/response/ChangeNotificationResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/ChangePasswordResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/ChangeProfileResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/CheckBadgeApplyResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/CreateBadgeApplyResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/ExistsEmailResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/ExistsNickNameResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/KakaoLoginResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/LoginResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/LogoutResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/ReissueResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/ResetPasswordResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/SendCodeForPasswordResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/SendCodeForSignupResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/SignUpResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/UserFeedListResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/UserProfileResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/UserRestaurantListResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/UserSearchResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/UserThumbnailResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/VerifiedCodeResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/WithdrawResp.java
  application/src/main/java/com/foodielog/application/user/service/UserAuthService.java
  application/src/main/java/com/foodielog/application/user/service/UserOauthService.java
  application/src/main/java/com/foodielog/application/user/service/UserService.java
  application/src/main/java/com/foodielog/application/user/service/UserSettingService.java
Labels: ♻️ Refactor

#108 [Refactor] #107 swagger 주석 처리 제거, errors 제거
  application/src/main/java/com/foodielog/application/_core/swagger/ApplicationSwaggerConfig.java
  application/src/main/java/com/foodielog/application/feed/dto/request/LikeFeedReq.java
  application/src/main/java/com/foodielog/application/feed/dto/request/ReportFeedReq.java
  application/src/main/java/com/foodielog/application/feed/dto/request/UpdateFeedReq.java
  application/src/main/java/com/foodielog/application/restaurant/controller/RestaurantController.java
Labels: ♻️ Refactor

#110 [Refactor] #96 코드 리팩토링
  application/src/main/java/com/foodielog/application/feed/controller/FeedController.java
  application/src/main/java/com/foodielog/application/feed/dto/response/MainFeedListResp.java
  application/src/main/java/com/foodielog/application/feed/service/FeedService.java
  application/src/main/java/com/foodielog/application/restaurant/controller/RestaurantController.java
  application/src/main/java/com/foodielog/application/restaurant/dto/response/RestaurantFeedListResp.java
  application/src/main/java/com/foodielog/application/restaurant/service/RestaurantService.java
  core/src/main/java/com/foodielog/server/feed/repository/FeedRepository.java
  core/src/main/java/com/foodielog/server/user/repository/FollowRepository.java
Labels: ♻️ Refactor

#113 [Fix} #112 비밀번호 인코딩
  application/src/main/java/com/foodielog/application/user/service/UserAuthService.java
Labels: 🐛 Bug

#121 [Feat] #120 관리자 서버 로그인, 토큰 발급 구현
  application/src/main/resources/data.sql
  build.gradle
  core/src/main/java/com/foodielog/server/user/repository/UserRepository.java
  management/src/main/java/com/foodielog/management/user/controller/UserAuthController.java
  management/src/main/java/com/foodielog/management/user/dto/request/LoginReq.java
  management/src/main/java/com/foodielog/management/user/dto/response/LoginResp.java
  management/src/main/java/com/foodielog/management/user/dto/response/ReissueResp.java
  management/src/main/java/com/foodielog/management/user/service/UserAuthService.java
  management/src/main/resources/data.sql
Labels: ✨ Feature
