Repository FoodieLog/foodie-log-server, pull requests merged in 2023-10, with the labels that each got.

#196 [Feat] #195 알람용 단일 피드 보기 기능 구현
  application/src/main/java/com/foodielog/application/feed/controller/FeedController.java
  application/src/main/java/com/foodielog/application/feed/dto/response/GetFeedResp.java
  application/src/main/java/com/foodielog/application/feed/service/FeedService.java
Labels: ✨ Feature

#198 [Fix] #197 reissue 시 토큰 무효화 로직 추가
  application/src/main/java/com/foodielog/application/user/service/UserAuthService.java
  application/src/main/java/com/foodielog/application/user/service/UserSettingService.java
  core/src/main/java/com/foodielog/server/_core/security/jwt/JwtTokenProvider.java
Labels: 🐛 Bug

#200 [Feat] #199 팔로우, 팔로워 목록 기능 구현
  application/src/main/java/com/foodielog/application/user/controller/UserController.java
  application/src/main/java/com/foodielog/application/user/dto/response/FollowListResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/FollowerListResp.java
  application/src/main/java/com/foodielog/application/user/service/UserService.java
  core/src/main/java/com/foodielog/server/user/repository/FollowRepository.java
Labels: ✨ Feature

#203 [Refactor] #202 업로드한 맛집 목록 응답값에 닉네임 추가
  application/src/main/java/com/foodielog/application/user/dto/response/UserRestaurantListResp.java
  application/src/main/java/com/foodielog/application/user/service/UserService.java
Labels: ♻️ Refactor

#204 [Fix] #201 알림 기능 시간 데이터 추가
  application/src/main/java/com/foodielog/application/notification/dto/response/NotificationListResp.java
Labels: 🐛 Bug

#210 [Fix] #209 차단 및 탈퇴 유저 팔로우에서 제외
  core/src/main/java/com/foodielog/server/user/repository/FollowRepository.java
Labels: 🐛 Bug

#214 [Fix] #213 유저 맛집 지도 목록에서 맛집 중복 체크 추가
  application/src/main/java/com/foodielog/application/user/service/UserService.java
Labels: 🐛 Bug
