Repository FoodieLog/foodie-log-server, pull requests merged in 2023-09, with the labels that each got.

#132 [Fix] #131 신고 횟수 카운트 쿼리 수정
  core/src/main/java/com/foodielog/server/report/repository/ReportRepository.java
  management/src/main/java/com/foodielog/management/report/service/ReportService.java
Labels: 🐛 Bug

#136 [Refactor] #124 단일 피드 맛집 정보 추가
  application/src/main/java/com/foodielog/application/feed/dto/response/FeedDetailResp.java
  application/src/main/java/com/foodielog/application/feed/service/FeedService.java
Labels: ♻️ Refactor

#139 [Fix] #138 유저 차단 시에 삭제 처리 및 메일 전송 수정
  management/src/main/java/com/foodielog/management/member/service/MemberService.java
Labels: 🐛 Bug

#142 [Refactor] #141 로그인 응답값 email 추가
  application/src/main/java/com/foodielog/application/user/dto/response/KakaoLoginResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/LoginResp.java
Labels: ♻️ Refactor

#145 [feat] #144 https healtycheck 컨트롤러
  application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java
  management/src/main/java/com/foodielog/management/user/controller/UserAuthController.java
Labels: ✨ Feature, 🌏 Deploy

#143 [Fix] #137 신고 승인 시 컨텐츠 삭제
  management/src/main/java/com/foodielog/management/report/controller/ReportController.java
  management/src/main/java/com/foodielog/management/report/service/ReportService.java
Labels: 🐛 Bug

#147 [Fix] #146 유저 프로필 닉네임 누락 수정
  application/src/main/java/com/foodielog/application/user/dto/response/UserProfileResp.java
Labels: 🐛 Bug

#150 [Fix] #149 auth 컨트롤러 앞에 prefix(api 또는 admin) 추가
  application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java
  core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java
  management/src/main/java/com/foodielog/management/user/controller/UserAuthController.java
Labels: 🌏 Deploy, ♻️ Refactor

#151 [Refactor] #148 피드 및 댓글 userId 응답 값 추가
  application/src/main/java/com/foodielog/application/feed/dto/response/FeedDetailResp.java
  application/src/main/java/com/foodielog/application/feed/dto/response/MainFeedListResp.java
  application/src/main/java/com/foodielog/application/reply/dto/response/ReplyCreatResp.java
  application/src/main/java/com/foodielog/application/restaurant/dto/response/RestaurantFeedListResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/UserFeedListResp.java
Labels: ♻️ Refactor

#153 [Fix] #152 CORS AllowedOrigins 설정
  core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java
Labels: 🌏 Deploy

#154 fix: 서버 url 오타 수정
  core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java
Labels: 🐛 Bug

#158 [Refactor] #157 로그인 응답값에 알림 설정 상태 추가
  application/src/main/java/com/foodielog/application/user/dto/response/KakaoLoginResp.java
  application/src/main/java/com/foodielog/application/user/dto/response/LoginResp.java
Labels: ♻️ Refactor

#162 [Refactor] #161 더미데이터 수정
  application/src/main/resources/application.yml
  application/src/main/resources/data.sql
  core/src/main/java/com/foodielog/server/admin/entity/BlockUser.java
  management/src/main/resources/application.yml
  management/src/main/resources/data.sql
Labels: ♻️ Refactor

#174 [Refactor] #173 회원가입 시 파일 선택 입력으로 변경
  application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java
  application/src/main/java/com/foodielog/application/user/service/UserAuthService.java
Labels: ♻️ Refactor

#175 [Feature] #166 AllowedOrigins 추가
  core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java
Labels: ✨ Feature, 🌏 Deploy

#183 [Refactor] #181 s3 파일 저장 시 null 체크 추가
  core/src/main/java/com/foodielog/server/_core/s3/S3Uploader.java
Labels: ♻️ Refactor

#188 [Feat] #187 카카오 중복 체크 api
  application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java
  application/src/main/java/com/foodielog/application/user/dto/response/ExistsKakaoResp.java
  application/src/main/java/com/foodielog/application/user/service/UserOauthService.java
Labels: ✨ Feature

#190 refactor: 카카오 중복체크 응답 상태코드 변경 (#189)
  application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java
Labels: ♻️ Refactor

#192 [Fix] #191 프로필 회원 정보 오류 수정
  application/src/main/java/com/foodielog/application/user/service/UserService.java
Labels: 🐛 Bug

#194 [Fix] #193 메인 피드 리스트 페이징 오류 수정
  core/src/main/java/com/foodielog/server/feed/repository/FeedRepository.java
Labels: 🐛 Bug
